version: '3.8'

services:
  mongo1:
    image: mongo:4.0
    container_name: mongo1
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - mongo-net
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo:4.0
    container_name: mongo2
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-net
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo:4.0
    container_name: mongo3
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-net
    volumes:
      - mongo3-data:/data/db

  mongo-init:
    image: mongo:4.0
    container_name: mongo-init
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-net
    volumes:
      - ./init/mongo/init-replica.sh:/init-replica.sh
    entrypoint: ["/bin/sh", "/init-replica.sh"]

networks:
  mongo-net:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

